insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Isadore Maass', '5142566737', null, '37863 Tennessee Parkway');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Levey Bynold', '2085173795', null, '3 Crownhardt Junction');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Audie Spere', '1539590244', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Angie Papierz', '1548635990', null, '53833 Victoria Drive');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Jude Addis', '8436673873', null, '44 3rd Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Cassandre Blackader', '8208858738', null, '2721 Park Meadow Drive');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Maighdiln Deniske', '7033129794', null, '9910 Mcguire Junction');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Lin Van der Brug', '7893631873', null, '9 Judy Plaza');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Lucas Toward', '7354567605', null, '73753 Chive Terrace');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Odie Hucquart', '1414525472', null, '1740 Declaration Court');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Berty Roumier', '9131789191', null, '2 Gateway Pass');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Henderson Kikke', '9782990508', 'hkikkeb@businesswire.com', '2013 Lien Road');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Andrew Colliss', '2123633911', 'acollissc@unblog.fr', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Guenevere Belison', '3493350633', null, '69534 Mallard Parkway');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Coraline Starte', '8664431449', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Berthe Beekman', '2155330503', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Tad Norewood', '2327404092', 'tnorewoodg@blogs.com', '2 Bonner Plaza');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Andria O''Gormley', '8737213331', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Lucine Khristyukhin', '8779302943', 'lkhristyukhini@newsvine.com', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Elfie Whiteside', '8067279402', null, '626 Bonner Court');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Ashley Shurman', '3758941154', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Willamina Olkowicz', '4239207866', null, '7 Atwood Place');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Theda Pettigree', '8487212134', 'tpettigreem@google.pl', '11920 Eggendart Point');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Constantino Pech', '6837207124', 'cpechn@ftc.gov', '6 Prairie Rose Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Seamus Guilfoyle', '9924061674', 'sguilfoyleo@indiegogo.com', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Pris Leman', '3392551158', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Kin Catcherside', '3643632009', 'kcatchersideq@boston.com', '1 Hoffman Plaza');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Mamie Wheeler', '4992100347', 'mwheelerr@dailymotion.com', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Halimeda Domke', '6819044484', 'hdomkes@cdc.gov', '097 Packers Trail');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Darby Crossthwaite', '5135716526', null, '4 Ridge Oak Crossing');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Abram Cambden', '7718421345', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Pincas Pedden', '3735289064', null, '1 Barnett Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Margette Langan', '4833915632', null, '1 Lakewood Gardens Point');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Juan Downey', '6494252518', null, '7 Continental Way');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Donavon Rainville', '8639389627', null, '7 Sutherland Point');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Clareta Place', '3363936481', 'cplacez@mayoclinic.com', '0 Stephen Trail');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Edgardo Foxen', '2043987858', null, '49533 Dixon Drive');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Sephira Somerled', '8778030427', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Ahmed Dimmick', '8752643016', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Stinky Jarrard', '5309113145', null, '6 Evergreen Way');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Alleen Spellward', '3819001116', 'aspellward14@squarespace.com', '147 Warner Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Ulises Cecely', '9431293426', 'ucecely15@blinklist.com', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Edita Dumbelton', '3977389351', null, '71951 Kipling Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Tana Coughtrey', '8501059899', null, '37 Pierstorff Center');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Tiena Meineken', '5053731629', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Hunt Brogden', '6986504614', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Leslie Tremain', '2342803916', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Ruth Bulcock', '3822319603', null, '234 Forest Dale Center');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Kylie Albion', '4816093675', 'kalbion1c@ox.ac.uk', '591 Steensland Drive');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Wilt Selbach', '6532775522', 'wselbach1d@sourceforge.net', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Jacquetta Lavies', '8904887860', 'jlavies1e@adobe.com', '67078 Pine View Terrace');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Marline Hiscocks', '4904181281', 'mhiscocks1f@mail.ru', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Carlin Bailles', '8522161209', 'cbailles1g@google.com.br', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Aldrich Radloff', '1047810492', null, '72 Mayfield Way');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Mellicent MacCartair', '1887373283', 'mmaccartair1i@china.com.cn', '1 Fallview Road');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Zelig Peinke', '4952260673', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Carol Kingzeth', '9886065196', null, '2 Surrey Place');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Lorinda Ianitti', '8708251706', 'lianitti1l@cisco.com', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Harrison Humphery', '8797359044', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Tailor Rumsby', '5628448869', null, '2 Vera Junction');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Allix Hindmore', '8124088599', 'ahindmore1o@chicagotribune.com', '2115 Maywood Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Cairistiona Stockall', '6126993911', null, '852 Park Meadow Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Jenifer Bransom', '3131290036', null, '49 Meadow Vale Trail');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Cart Deakin', '8922118956', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Lillian von Hagt', '6303971505', 'lvon1s@sakura.ne.jp', '98051 New Castle Drive');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Gaylene Baldi', '2125346726', 'gbaldi1t@purevolume.com', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Ethelda Haynesford', '4706954840', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Cortie Marrow', '1014683793', 'cmarrow1v@hostgator.com', '78 Stang Trail');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Cacilia Brocklebank', '1395212994', 'cbrocklebank1w@webs.com', '30024 David Way');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Margit Ladbury', '4969451299', 'mladbury1x@weibo.com', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Natassia Calles', '5534610193', 'ncalles1y@shutterfly.com', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Shepherd Healks', '2054299420', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Ron Fawkes', '8927479007', null, '85 Dunning Road');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Marty Siehard', '1031653292', null, '440 Kennedy Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Stanton Dey', '6787281583', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Katlin Coulsen', '8745222405', null, '1 Blaine Plaza');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Susi Beardall', '5417354573', 'sbeardall24@addthis.com', '228 Waxwing Circle');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Ulrikaumeko Boise', '9389481410', null, '89477 Magdeline Parkway');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Shaina MacLardie', '4746132350', null, '81 Old Shore Trail');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Molli Laneham', '9713793919', 'mlaneham27@accuweather.com', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Zarah Livens', '6377644384', 'zlivens28@cnn.com', '415 Monterey Street');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Marlow Hartford', '1172573043', null, '56 North Pass');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Edgard McNelly', '7275021332', null, '910 Declaration Junction');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Junie Dabnor', '2601210540', 'jdabnor2b@weibo.com', '62567 Clarendon Crossing');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Kenneth Domotor', '6461941647', 'kdomotor2c@hugedomains.com', '38489 John Wall Lane');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Stefania Ziemen', '2356781272', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Fabien Dumbreck', '1123851813', null, '95425 Atwood Road');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Amity Grent', '8553256604', 'agrent2f@bigcartel.com', '89 Schlimgen Terrace');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Juliet Esson', '2303358829', 'jesson2g@taobao.com', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Reilly Auchterlonie', '9401031017', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Roman Bailes', '9468760161', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Melisenda Oddboy', '2862192541', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Annora Stranio', '1371032178', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Mala O'' Mahony', '8164943373', null, '3 Talmadge Junction');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Geneva Colleran', '6244444257', null, '661 Mosinee Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Guido Watters', '2833179680', null, '2943 Florence Hill');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Andre Brabham', '8089844851', null, '6986 Hooker Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Douglas Lanning', '2823040726', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Jordon Abramowitch', '2355671677', null, '3129 Loomis Road');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Lalo Prahl', '9143051520', null, '667 Mccormick Pass');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Marion Janik', '8598071195', null, '8401 Emmet Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Inessa Vaggs', '6398046423', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Hebert Delph', '9748498519', null, '75770 Oneill Hill');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Rourke Mighele', '8311053264', null, '028 Summerview Street');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Yettie Farncomb', '4066901741', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Loni Drabble', '1688514304', null, '48043 Valley Edge Circle');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Otis Hubberstey', '2854884021', null, '113 Weeping Birch Hill');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Arline Scrase', '6395598413', 'ascrase2z@toplist.cz', '57 Orin Circle');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Lissie McNirlan', '1569811805', 'lmcnirlan30@mlb.com', '1 Hallows Terrace');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Neils Newvill', '4253548703', 'nnewvill31@vistaprint.com', '9 Almo Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Mignonne Cruse', '3593825478', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Meris Huckerbe', '7051482906', null, '52 Portage Circle');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Dex Evenett', '9229356146', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Gabriell Heugle', '7286687934', 'gheugle35@vimeo.com', '31 3rd Alley');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Roxanna Cunningham', '3156667467', null, '3 Arrowood Alley');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Shirline Schruyers', '3558092707', null, '79283 Gina Trail');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Kinsley Ugo', '6378758762', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Opal Sanbrooke', '1978464203', 'osanbrooke39@gov.uk', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Constantine Moores', '5154997385', 'cmoores3a@odnoklassniki.ru', '207 Heath Hill');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Gui Castelli', '5012240422', null, '5 Karstens Point');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Zach Karolczyk', '6244907793', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Normie Calvey', '5657996465', 'ncalvey3d@yellowbook.com', '9 Springview Crossing');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Lannie Kilbee', '8003147735', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Adrea McGragh', '2588170513', null, '0623 Vera Court');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Emlen Maddrah', '8751417412', null, '5209 Vahlen Point');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Ashlie Cowern', '5108419170', 'acowern3h@cbsnews.com', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Di Fewkes', '3829364312', 'dfewkes3i@altervista.org', '37 Mayfield Point');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Minta Newe', '7954828890', 'mnewe3j@narod.ru', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Clea Geroldi', '1674442299', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Gery Fishly', '7727487881', 'gfishly3l@businesswire.com', '1 Cordelia Alley');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Sephira Toye', '3502506072', null, '1628 Utah Center');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Leta Beggi', '2339633864', 'lbeggi3n@ebay.co.uk', '5387 Walton Road');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Luther Gasparro', '8522201691', 'lgasparro3o@xing.com', '14 Green Ridge Terrace');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Maxy Flaubert', '9121605317', 'mflaubert3p@sfgate.com', '3290 Thackeray Place');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Georgeanna Gwalter', '6578513779', 'ggwalter3q@guardian.co.uk', null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Roman O''Mailey', '1931706998', null, '547 Dorton Center');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Kendal Flori', '9041714648', 'kflori3s@youku.com', '9463 Amoth Parkway');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Rosmunda Kezourec', '5128587723', 'rkezourec3t@who.int', '572 Graceland Drive');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Jilli Sudy', '6812552110', null, '00 Sommers Point');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Marylee Bruhnsen', '9081220510', 'mbruhnsen3v@smh.com.au', '8 Sunbrook Center');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Seth Trowler', '7157936974', 'strowler3w@instagram.com', '26345 Victoria Way');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Fay Domenge', '8119410579', null, '2134 Northland Lane');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Kinsley Lawey', '3828439707', null, '229 Mandrake Point');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Simone Nudds', '4874190132', 'snudds3z@themeforest.net', '6722 7th Park');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Joleen Georgot', '1188651284', null, '1957 Summer Ridge Terrace');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Prent Cocklie', '6588719438', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Clywd Sigars', '4079454252', null, '1777 Weeping Birch Terrace');
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Dominique Givens', '3898000528', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Lothario Woollin', '9311942258', null, null);
insert into Clients (cl_name, cl_phone, cl_mail, cl_addr) values ('Maren Baudains', '8405899703', null, '36705 Badeau Center');
